services:
  postgres: 
    image: postgres:16
    container_name: store-db
    restart: always
    environment:
        - POSTGRES_DB=store
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports: 
      - 5432:5432