<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
      <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Store.Notifications.Domain\Store.Notifications.Domain.csproj" />
    </ItemGroup>

</Project>
